version: '3.8'

services:
  claude-share:
    build: .
    platform: linux/amd64
    container_name: claude-share-prod
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
      - WORKERS=4
      - LOG_LEVEL=info
    volumes:
      # Persist session data
      - ./claude_sessions:/app/claude_sessions
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Production optimizations for Linux VM
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
